name: Generate Bosnia-Herzegovina Tiles

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    uses: ./.github/workflows/generate-tiles.yml
    with:
      country: bosnia-herzegovina
    secrets: inherit
