name: Generate Lithuania Tiles

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate and publish country tiles
        uses: ./.github/actions/generate-country-tiles
        with:
          country: lithuania
