name: Generate Albania Tiles

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    uses: ./.github/workflows/generate-tiles.yml
    with:
      country: albania
    secrets: inherit
